### ISSUE TITLE
Add discussion as features of project

### ISSUE THREAD

**Issue by Vaadasch** [utilityresearchlab/scg-3d-printing#1]
Hi,
Could you add the discussion feature of the github project ?
I would like to inform you about this study : https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8753602/
Adding Calcium ions to the solution could improve the structure.
I'm currently disolving egg shells in white vinegar and lemon juice (separately) in order to test it, but i don't have the scientifical processes to be rigorous

**Comment by mriveralee** [comment]
Hi @Vaadasch -- thanks for the suggestion! I've opened up the discussions feature. Feel free to move your idea/suggestion over there for others to discuss.
